# ISSUE TEMPLATE

name: Issue Template
description: General template for new issues
title: "[Issue] - "
labels: ["feat"]
projects: ["esther-poniatowski/mtcdb-track"]
assignees: esther-poniatowski
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: Brief statement of the goal.
      placeholder: ...
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Background
      description: Context or reason for this feature/fix.
      placeholder: ...

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        -

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      placeholder: |
        1.

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      placeholder: |
	      - Related to

  - type: textarea
    id: related_files
    attributes:
      label: Related Files
      placeholder: |
        - Branch (URL)
        - File (URL)
        - Code (URL)

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional information or considerations.
      placeholder: ...
