# =================================================================================
# map_deploy.yml
# Map paths in local and remote servers to deploy a part of the codebase to the data hub.
#
# Structure and Format: See conventions in `tasks.network.transfer`.
# =================================================================================

- source: setup/hub/meta.env
  destination: ./
- source: setup/hub/path.env
  destination: ./
- source: setup/hub/environment.yml
  destination: setup/
- source: src/tasks/network/mount_data.sh
  destination: ops/
- source: src/ingest/
  destination: src/
