# =================================================================================
# Mapping between paths in local and remote servers for deployment.
#
# Directories and individual files to transfer are mapped in the following format:
# directories:
#   - local: <local_directory>
#     remote: <remote_directory>
# files:
#   - local: <local_file>
#     remote: <remote_dir>
#
# Warning
# -------
# Paths are *relative* to the *root* directory of the workspace in the respective servers.
# For files, the remote path should be the destination *directory*, not a file path.
# =================================================================================

directories:
  - local: src/mtcdb_hub
    remote: src/mtcdb
  - local: config/hub
    remote: config

files:
  - local:
  - remote:
