"""
:mod:`test_core.test_preprocess.test_hierarchical_bootstrap` [module]

See Also
--------
:mod:`core.processors.preprocess.bootstrap`: Tested module.
:func:`assert_array_equal`: Numpy testing function for array equality.
"""
# Disable error for properties defined by the metaclass
# pylint: disable=no-member

# Disable error for internal attributes access
# pylint: disable=protected-access

# Disable error for no assignment in assert
# pylint: disable=expression-not-assigned

import numpy as np
from numpy.testing import assert_array_equal
import pytest

from core.processors.preprocess.bootstrap import Bootstrapper


def test_pick_trials_equal():
    """
    Tests for :func:`Bootstrapper.pick_trials`, case where ``n == n_pseudo``.

    Test Inputs
    -----------
    n = 3
    n_pseudo = 3

    Expected Outputs
    ----------------
    Each trial number is selected exactly once.
    expected_count = np.array([1, 1, 1])

    See Also
    --------
    :func:`numpy.bincount`:
        Count the number of occurrences of each value in an array of non-negative integers.
        Output: Array where the index represents the unique values in the input array, and the
        corresponding value represents the count of occurrences.
        Example: ``np.bincount([0, 1, 1, 3])`` returns ``array([1, 2, 0, 1])``,
        which means that 0 occurs once, 1 occurs twice, 2 occurs zero times, and 3 occurs once.
    """
    n, n_pseudo = 3, 3
    bootstrapper = Bootstrapper(n_pseudo=n_pseudo)
    trials = bootstrapper.pick_trials(n)
    occurrences = np.bincount(trials, minlength=n)
    expected = np.array([1, 1, 1])
    assert_array_equal(occurrences, expected), f"Occurrences: {occurrences} != {expected}"


def test_pick_trials_greater():
    """
    Tests for :func:`pick_trials`, case where ``n > n_pseudo``.

    Test Inputs
    -----------
    n = 5
    n_pseudo = 3

    Expected Outputs
    ----------------
    n_pseudo trials are selected only once.
    n - n_pseudo trials are not selected.
    expected_nb_1 = n_pseudo
    expected_nb_0 = n - n_pseudo
    """
    n, n_pseudo = 5, 3
    bootstrapper = Bootstrapper(n_pseudo=n_pseudo)
    trials = bootstrapper.pick_trials(n)
    # Count the number of occurrences of each trial index
    count_occurrences = np.bincount(trials, minlength=n)
    # Count the number of 1 and O in `counts` itself
    nb_1 = np.count_nonzero(count_occurrences == 1)
    nb_0 = np.count_nonzero(count_occurrences == 0)
    expected_1 = n_pseudo
    expected_0 = n - n_pseudo
    assert nb_1 == expected_1, f"Expected {expected_1}, Got {nb_1}"
    assert nb_0 == expected_0, f"Expected {expected_0}, Got {nb_0}"


def test_pick_trials_smaller():
    """
    Tests for :func:`pick_trials`, case where ``n < n_pseudo``.

    Test Inputs
    -----------
    n = 3
    n_pseudo = 8

    Expected Outputs
    ----------------
    q = n_pseudo // n = 8 // 3 = 2
    r = n_pseudo % n = 8 % 3 = 2
    Each trial is selected at least q times and r trials are selected one more time.
    Thus n - r trials are selected q times and r trials are selected q + 1 times.
    expected_nb_q = n - r
    expected_nb_q_plus_1 = r
    """
    n, n_pseudo = 3, 8
    q, r = divmod(n_pseudo, n)
    bootstrapper = Bootstrapper(n_pseudo=n_pseudo)
    trials = bootstrapper.pick_trials(n)
    # Count the number of occurrences of each trial index
    counts = np.bincount(trials, minlength=n)
    # Count the number of trials selected q times and q + 1 times
    nb_q = np.count_nonzero(counts == q)
    nb_q_plus_1 = np.count_nonzero(counts == q + 1)
    expected_q = n - r
    expected_q_plus_1 = r
    assert nb_q == expected_q, f"Expected {expected_q}, Got {nb_q}"
    assert nb_q_plus_1 == expected_q_plus_1, f"Expected {expected_q_plus_1}, Got {nb_q_plus_1}"


def test_bootstrap():
    """
    Tests for :func:`bootstrap`.

    Test Inputs
    -----------
    n_units = 3
    counts = np.array([3, 5, 7])
    n_pseudo = 5

    Expected Outputs
    ----------------
    Shape of the output array: (n_units, n_pseudo)
    Each item should be less than the corresponding count value, because the pseudo-trials are
    generated by sampling with replacement from the original counts. Thus, the maximum value of the
    pseudo-trials should be less than the corresponding count value.
    """
    counts = np.array([3, 5, 7])
    n_units = len(counts)
    n_pseudo = 5
    expected_shape = (n_units, n_pseudo)
    bootstrapper = Bootstrapper(n_pseudo=n_pseudo)
    bootstrapper.counts = counts  # set manually
    bootstrapper.bootstrap()
    pseudo_trials = bootstrapper.pseudo_trials
    shape = pseudo_trials.shape
    assert shape[0] == n_units, f"Expected {n_units} units, Got {shape[0]}"
    assert shape[1] == n_pseudo, f"Expected {n_pseudo} trials, Got {shape[1]}"
    assert shape == expected_shape, f"Expected shape {expected_shape}, Got {shape}"
    assert np.all(pseudo_trials < counts[:, None]), f"Items out of bounds: {pseudo_trials}"


def test_process():
    """
    Test for :func:`Bootstrapper.process` method (base class).

    Test Inputs
    -----------
    See :func:`test_bootstrap` for inputs.

    Expected Outputs
    ----------------
    """
    counts = np.array([3, 5, 7])
    n_units = len(counts)
    n_pseudo = 5
    bootstrapper = Bootstrapper(n_pseudo=n_pseudo)
    bootstrapper.process(counts=counts)  # without n_pseudo, should be set to n_global
    pseudo_trials = bootstrapper.pseudo_trials
    shape = pseudo_trials.shape
    assert shape[0] == n_units, f"Expected {n_units} units, Got {shape[0]}"
    assert shape[1] == n_pseudo, f"Expected {n_pseudo} trials, Got {shape[1]}"
    assert np.all(pseudo_trials < counts[:, None]), f"Items out of bounds: {pseudo_trials}"


def test_pseudo_trials_reproducibility_with_seed():
    """
    Test :meth:`Bootstrapper.pseudo_trials` reproducibility with a fixed seed.

    Test Inputs
    -----------
    counts = [10, 8, 12]
    seed = 42

    Expected Outputs
    ----------------
    pseudo_trials should be the same when the seed is fixed.
    """
    counts = np.array([10, 8, 12])
    bootstrapper = Bootstrapper(n_pseudo=5)
    bootstrapper.process(counts=counts, seed=42)
    pseudo_trials_1 = bootstrapper.pseudo_trials.copy()
    # Create a new instance with the same seed and ensure results are reproducible
    bootstrapper.process(counts=counts, seed=42)
    pseudo_trials_2 = bootstrapper.pseudo_trials.copy()
    assert_array_equal(pseudo_trials_1, pseudo_trials_2), "Pseudo-trials not reproduced"
